services:
  my-web-app: 
    build:
      context: . 
    env_file: .env 
    ports: 
      - 8042:8000 
  my-db: 
    image: postgres 
    ports: 
      - 5453:5432 
    volumes: 
      - ./db_data:/var/lib/postgres 
    environment: 
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=banks 
