services:
  my-web-app: 
    build:
      context: . 
    env_file: .env 
    environment:
      - DB_HOST=my-db 
      - DB_PORT=5432
    ports: 
      - 8042:8000 
  my-db: 
    image: postgres 
    ports: 
      - 5453:5432 
    volumes: 
      - ./db_data:/var/lib/postgres 
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
