services:
  my-db: 
    image: postgres 
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"] 
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports: 
      - 5453:5432 
    volumes: 
      - ./db_data:/var/lib/postgresql/data
  my-web-app: 
    build:
      context: . 
    env_file: .env 
    depends_on: 
      my-db: 
        condition: service_healthy 
    ports: 
      - 8042:8000 
