services:
  my-web-app: 
    build:
      context: . 
    env_file: .env 
    environment:
      - DB_HOST=my-db    
      - DB_PORT=5432
    depends_on: 
      my-db: 
        condition: service_healthy 
    ports: 
      - 8042:8000 
  my-db: 
    image: postgres 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"] 
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports: 
      - 5453:5432 
    volumes: 
      - ./db_data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
