"""File with constants."""

MAX_LENGTH_USERNAME = 65
MIN_LENGTH_USERNAME = 65
MAX_LENGTH_DESCRIPTION = 500
MAX_DIGITS_AMOUNT = 15
MAX_DIGITS_BANK_ACCOUNT = 40
MAX_LENGTH_PHONE = 12
MAX_LENGTH_FIRST_NAME = 70
MAX_LENGTH_LAST_NAME = 100
