# Generated by Django 5.0.3 on 2024-04-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS banks",
            "DROP SCHEMA IF EXISTS banks"
        )
    ]
