# Generated by Django 5.0.3 on 2024-04-28 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('foundation_date', models.DateField()),
            ],
            options={
                'verbose_name': 'bank',
                'verbose_name_plural': 'banks',
                'db_table': '"banks"."bank"',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('banks', models.ManyToManyField(to='banks_app.bank')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': '"banks"."client"',
                'ordering': ['first_name', 'last_name', 'phone'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=40)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banks_app.client')),
            ],
            options={
                'verbose_name': 'bank_account',
                'verbose_name_plural': 'bank_accounts',
                'db_table': '"banks"."bank_account"',
                'ordering': ['balance', 'client'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('from_bank_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='banks_app.bankaccount')),
                ('initializer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='initializer', to='banks_app.client')),
                ('to_bank_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='banks_app.bankaccount')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'db_table': '"banks"."transaction"',
                'ordering': ['initializer', 'amount', 'transaction_date', 'description', 'from_bank_account_id', 'to_bank_account_id'],
            },
        ),
        migrations.CreateModel(
            name='BankClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.bank', verbose_name='bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'relationship bank client',
                'verbose_name_plural': 'relationships bank client',
                'db_table': '"banks"."bank_client"',
                'unique_together': {('bank', 'client')},
            },
        ),
        migrations.CreateModel(
            name='BankAccountClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.bankaccount', verbose_name='bank_account')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'relationship bank_account client',
                'verbose_name_plural': 'relationships bank_account client',
                'db_table': '"banks"."bank_account_client"',
                'unique_together': {('bank_account', 'client')},
            },
        ),
        migrations.CreateModel(
            name='TransactionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.client', verbose_name='transaction')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks_app.transaction', verbose_name='client')),
            ],
            options={
                'verbose_name': 'relationship transaction client',
                'verbose_name_plural': 'relationships transaction client',
                'db_table': '"banks"."transaction_client"',
                'unique_together': {('transaction', 'client')},
            },
        ),
    ]
