name: Проверка
on: [push]
jobs:
  linter_backend:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8 . 
  container-job:
    name: Тесты 
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5453
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
        - 5453:5432
    steps:
    - uses: actions/checkout@v2
    - name: Python installation
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Dependencies installation
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        chmod +x testing/test.sh
    - name: Test views
        run: testing.test_views
      # run: ./testing/test.sh testing.test_views